<?php
//Creado con Ardora - www.webardora.net
//bajo licencia Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
//para otros usos contacte con el autor
session_cache_limiter("nocache,private");session_start();$slogin_noauthpage=0;$slogin_pagetitle="";$usr=$_SESSION["Username"];
require("../../../../../php/paraUsu.php");
$db=new SQLite3("../../../../../db/usuarios.db") or die("Unable to open database");
include_once("para.php");$folderN="../../../".folderWork;$folUser=$_SESSION["Username"];$xmlName=$_SESSION["Username"];
if($_POST["action"]=="new"){$ttt=$_POST["idNum"];if (file_exists($folderN.$_SESSION["Username"].".xml")){$xml=simplexml_load_file($folderN.$_SESSION["Username"].".xml");$index=0;$nItem=-1;foreach ($xml as $job){if ((string)$job->id===$_POST["idNum"]){unset($xml->job[$index]);break;};$index++;}
$xml->asXML($folderN.$_SESSION["Username"].".xml");$job=$xml->addChild("job");$idJob=$job->addChild("id",$ttt);$date=$job->addChild("date",date("d/m/Y"));$values=$_POST["taboaIntentos"];for($i=0; $i<count($values); $i++){
$attemp=$job->addChild("attemp");$indice=$attemp->addChild("indice",$values[$i]["ind"]);$hinicio=$attemp->addChild("hinicio",$values[$i]["hinicio"]);$intentos=$attemp->addChild("intentos",$values[$i]["intentos"]);$estado=$attemp->addChild("estado",$values[$i]["estado"]);$hfin=$attemp->addChild("hfin",$values[$i]["hfin"]);$puntos=$attemp->addChild("puntos",$values[$i]["puntos"]);};$xml->asXML($folderN.$_SESSION["Username"].".xml");}
else{$xml=new DomDocument("1.0","UTF-8");$initial=$xml->createElement("attemps");$initial=$xml->appendChild($initial);$job=$xml->createElement("job");$job=$initial->appendChild($job);$idJob=$xml->createElement("id",$ttt);$idJob=$job->appendChild($idJob);$date=$xml->createElement("date",date("d/m/Y"));$date=$job->appendChild($date);$values=$_POST["taboaIntentos"];
for($i=0; $i<count($values); $i++){$attemp=$xml->createElement("attemp");$attemp=$job->appendChild($attemp);$indice=$xml->createElement("indice",$values[$i]["ind"]);$indice=$attemp->appendChild($indice);$hinicio=$xml->createElement("hinicio",$values[$i]["hinicio"]);$hinicio=$attemp->appendChild($hinicio);$intentos=$xml->createElement("intentos",$values[$i]["intentos"]);
$intentos=$attemp->appendChild($intentos);$estado=$xml->createElement("estado",$values[$i]["estado"]);$estado=$attemp->appendChild($estado);$hfin=$xml->createElement("hfin",$values[$i]["hfin"]);$hfin=$attemp->appendChild($hfin);$puntos=$xml->createElement("puntos",$values[$i]["puntos"]);$puntos=$attemp->appendChild($puntos);}
$xml->formatOut=true;$strings_xml=$xml->saveXML();$xml->save($folderN.$xmlName.".xml");}}
if($_POST["action"]=="getIdNum"){$idNum=0;if (file_exists($folderN.$_SESSION["Username"].".xml")){$xml = new DOMDocument("1.0", "utf-8");$xml->formatOutput=true;$xml->preserveWhiteSpace=false;$xml->load($folderN.$_SESSION["Username"].".xml");$objJob=$xml->getElementsByTagName("job");foreach($objJob as $job){$num=$job->getElementsByTagName("id")->item(0)->nodeValue;if ($num>$idNum){$idNum=$num;}}}
$result = $db->query("SELECT * FROM users WHERE username='$usr'");$res=$result->fetchArray(SQLITE3_ASSOC);$nold=decod($res["fullsusername"],keynum);$ncur=decod($res["cur"],keynum);$ngru=decod($res["gru"],keynum);
$ntyp=decod($res["usertype"],keynum);echo json_encode(array("id" => $idNum,"userType"=>$ntyp,"userName"=>$nold,"userCur"=>$ncur,"userGru"=>$ngru));}
if($_POST["action"]=="getInfo"){$ecuser=array();$user=array();$user_n=array();$user_c=array();$user_g=array();$result=$db->query("SELECT * FROM users WHERE username='$usr'");$res=$result->fetchArray(SQLITE3_ASSOC);$nus=decod($res["username"],keynum);$nold=decod($res["fullsusername"],keynum);$ncur=decod($res["cur"],keynum);$ngru=decod($res["gru"],keynum);$ntyp=decod($res["usertype"],keynum);
if ($ntyp=="profe"){$r_cg=$db->query("SELECT * FROM teachers WHERE teacher='$usr'");while($rcg=$r_cg->fetchArray(SQLITE3_ASSOC)){$c=$rcg["cur"];$g=$rcg["gru"];$result = $db->query("SELECT * FROM users");while($res=$result->fetchArray(SQLITE3_ASSOC)){if (decod($res["usertype"],keynum)=="alu" && $res["cur"]==$c && $res["gru"]==$g ){
array_push($ecuser,$res["username"]);array_push($user,decod($res["username"],keynum));array_push($user_n,decod($res["fullsusername"],keynum));array_push($user_c,decod($res["cur"],keynum));array_push($user_g,decod($res["gru"],keynum));}}}}else{
$result = $db->query("SELECT * FROM users");while($res=$result->fetchArray(SQLITE3_ASSOC)){if (decod($res["usertype"],keynum)!="admin" && decod($res["usertype"],keynum)!="profe" && $res["username"]===$usr){array_push($ecuser,$res["username"]);array_push($user,decod($res["username"],keynum));array_push($user_n,decod($res["fullsusername"],keynum));array_push($user_c,decod($res["cur"],keynum));array_push($user_g,decod($res["gru"],keynum));}}}
array_multisort($user_c,SORT_ASC,$user_g,SORT_ASC,$user_n,SORT_ASC,$user,$ecuser);$jobs=array();$index=0;
for($i=0; $i<count($user); $i++){if (file_exists($folderN.$ecuser[$i].".xml")){$xml=new DOMDocument("1.0", "utf-8");$xml->formatOutput=true;$xml->preserveWhiteSpace = false;$xml->load($folderN.$ecuser[$i].".xml");$objJob=$xml->getElementsByTagName("job");
foreach($objJob as $job){$objAttemp=$job->getElementsByTagName("attemp");foreach($objAttemp as $att){$jobs[]=array("name"=>$user[$i],"jobid"=>$job->getElementsByTagName("id")->item(0)->nodeValue,"jobdate"=>$job->getElementsByTagName("date")->item(0)->nodeValue,
"attin"=>$att->getElementsByTagName("indice")->item(0)->nodeValue,"atthi"=>$att->getElementsByTagName("hinicio")->item(0)->nodeValue,"attemps"=>$att->getElementsByTagName("intentos")->item(0)->nodeValue,"attes"=>$att->getElementsByTagName("estado")->item(0)->nodeValue,
"atthf"=>$att->getElementsByTagName("hfin")->item(0)->nodeValue,"attpo"=>$att->getElementsByTagName("puntos")->item(0)->nodeValue);};$index++;}}};
echo json_encode(array("users" => $user, "user_n"=>$user_n, "user_c"=>$user_c, "user_g"=>$user_g, "jobs"=>$jobs,"userType"=>$ntyp ));}
if($_POST["action"]=="delItem"){$xmlPath=$folderN.encod($_POST["user"],keynum).".xml";if (file_exists($xmlPath)){$xml = new DOMDocument("1.0", "utf-8");$xml->formatOutput=true;$xml->preserveWhiteSpace=false;$xml->load($xmlPath);
$objItem=$xml->getElementsByTagName("job");$length=$objItem->length;for ($i=$length-1;$i>=0;$i--){$p=$objItem->item($i);$pid=$p->getElementsByTagName("id")->item(0)->nodeValue;if ($pid==$_POST["id"]){$parent=$p->parentNode;$parent->removeChild($p);}};$xml->save($xmlPath);}}
if($_POST["action"]=="getPersonalInfo"){$st=array();for ($i=0;$i<$_POST["size"];$i++){$st[$i]="0";};if ($slogin_profe[$i]!="admin" && $slogin_profe[$i]!="profe"){$xmlPath=$folderN.$_SESSION["Username"].".xml";
if (file_exists($xmlPath)){$xml=new DOMDocument("1.0","utf-8");$xml->formatOutput=true;$xml->preserveWhiteSpace=false;$xml->load($xmlPath);$objJob=$xml->getElementsByTagName("job");foreach($objJob as $job){$objAttemp=$job->getElementsByTagName("attemp");
foreach($objAttemp as $att){$state=$att->getElementsByTagName("estado")->item(0)->nodeValue;$in=$att->getElementsByTagName("indice")->item(0)->nodeValue;if ($state=="ok"){$st[intval($in)]="ok";}}}}};echo json_encode(array("state"=>$st));}
?>
