<?php
//Creado con Ardora - www.webardora.net
//bajo licencia Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
//para otros usos contacte con el autor
session_cache_limiter("nocache,private");session_start();$slogin_noauthpage=0;$slogin_pagetitle="";$usr=$_SESSION["Username"];require("../../php/paraUsu.php");
$db=new SQLite3("../../db/usuarios.db") or die("Unable to open database");
include_once ("cfg.php");include_once ("ardoraFileManagerFunctions.php");$result=$db->query("SELECT * FROM users WHERE username='$usr'");$res=$result->fetchArray(SQLITE3_ASSOC);$nus=decod($res["username"],keynum);$nold=decod($res["fullsusername"],keynum);$nful=$res["fullsusername"];$ncur=decod($res["cur"],keynum);$ngru=decod($res["gru"],keynum);$ntyp=decod($res["usertype"],keynum);
if($_POST["action"]=="getIdUser"){$allUser=array();if ($ntyp=="profe" || $ntyp=="admin"){$result1=$db->query("SELECT * FROM teachers WHERE teacher='$nus'");while($res1=$result1->fetchArray(SQLITE3_ASSOC)){$c=$res1["cur"];$g=$res1["gru"];
$result=$db->query("SELECT * FROM users WHERE cur='$c' AND gru='$g'");while($res=$result->fetchArray(SQLITE3_ASSOC)){$allUser[decod($res["username"],keynum)]=decod($res["fullsusername"],keynum);}}}
if ($ntyp=="profe" || $ntyp=="admin"){if (!file_exists("../".profeFold.$nus)){mkdir("../".profeFold.$nus, 0777);$file=fopen("../".profeFold.$nus."/index.php","a") or die();fputs($file,"<?php");fputs($file,"// Created by Ardora www.webardora.net");fputs($file,"//XARQUIVOS-dummy php");fputs($file,"?>");fclose($file);}}
else{if (!file_exists("../".aluFold.$nus)){mkdir("../".aluFold.$nus, 0777);$file=fopen("../".aluFold.$nus."/index.php","a") or die();fputs($file,"<?php");fputs($file,"// Created by Ardora www.webardora.net");fputs($file,"//XARQUIVOS-dummy php");fputs($file,"?>");fclose($file);}}
echo json_encode(array("allUser"=>$allUser,"userN"=>$nus,"userType"=>$ntyp,"userName"=>$nold,"userCur"=>$ncur,"userGru"=>$ngru));}
if($_POST["action"]=="getStateFolder"){$state="";if ($_POST["fType"]==0){$useSize=sizeDir(".."."/".sharedFold);$sMax=sizeMax;$state=format(sizeDir(".."."/".sharedFold))." / ".format(sizeMax);}
if ($_POST["fType"]==1){$tipo=$ntyp;if (($tipo=="profe") || ($tipo=="admin")){$useSize=sizeDir(".."."/".profeFold);$sMax=sizeMaxProf;$state=format(sizeDir(".."."/".profeFold))." / ".format(sizeMaxProf);}else{$useSize=sizeDir(".."."/".aluFold);$sMax=sizeMaxUser;$state=format(sizeDir(".."."/".aluFold))." / ".format(sizeMaxUser);}}
echo json_encode(array("state"=>$state,"useSize"=>$useSize,"sMax"=>$sMax));}
if($_POST["action"]=="makeDir"){$newDir=$_POST["fName"];if ($_POST["fType"]==0){$newDir=".."."/".sharedFold.$newDir;} if ($_POST["fType"]==1){$tipo=$ntyp;if (($tipo=="profe") || ($tipo=="admin")){$newDir=".."."/".profeFold.$nus."/".$newDir;}else{$newDir=".."."/".aluFold.$nus."/".$newDir;}} if ($_POST["fType"]==2){$newDir=".."."/".aluFold.$newDir;} if(!is_dir($newDir)){mkdir($newDir, 0777);}}
if($_POST["action"]=="deleteDir"){$newDir=$_POST["fName"];if ($_POST["fType"]==0){$newDir=".."."/".sharedFold.$newDir;} if ($_POST["fType"]==1){$tipo=$ntyp;if (($tipo=="profe") || ($tipo=="admin")){$newDir=".."."/".profeFold.$nus."/".$newDir;} else{$newDir=".."."/".aluFold.$nus."/".$newDir;}}
if ($_POST["fType"]==2){$newDir=".."."/".aluFold.$newDir;}if(is_dir($newDir)){deleteDir($newDir);$xml = new DOMDocument("1.0", "utf-8");$xml->load("../".xmlFile);$files = $xml->getElementsByTagName("file");foreach($files as $file) {$f=$file->getElementsByTagName("path")->item(0)->nodeValue;if (!file_exists($f)){$t=$file->getElementsByTagName("tab")->item(0)->nodeValue="5";}} $xml->save("../".xmlFile);$xmlF = simplexml_load_file("../".xmlFile);$cadena='//tab[.="5"]/parent::*';$result = $xmlF->xpath($cadena);foreach ($result as $r) unset ($r[0]);$xmlF->asXML("../".xmlFile);}}
if($_POST["action"]=="addXml"){$newDir=normaliza($_POST["fName"].$_POST["fileName"]);if ($_POST["fType"]==0){$newDir=".."."/".sharedFold.$newDir;} if ($_POST["fType"]==1){$tipo=$ntyp;if (($tipo=="profe") || ($tipo=="admin")){$newDir=".."."/".profeFold.$nus."/".$newDir;}else{$newDir=".."."/".aluFold.$nus."/".$newDir;}}if ($_POST["fType"]==2){$newDir=".."."/".aluFold.$newDir;}
$idNum=0;$theXmlFile=".."."/".xmlFile;$new=true;if (file_exists($theXmlFile)){$xml = new DOMDocument("1.0", "utf-8");$xml->formatOutput = true;$xml->preserveWhiteSpace = false;$xml->load($theXmlFile);$query="//files/file[path='".$newDir."']";$xpath = new DomXpath($xml);$tiFiles=$xpath->query($query);
foreach($tiFiles as $item){$new=false;$newItem = $xml->createElement("file");$newItem->appendChild($xml->createElement("tab",$_POST["fType"]));$newItem->appendChild($xml->createElement("path",$newDir));$newItem->appendChild($xml->createElement("usr",$nus));$newItem->appendChild($xml->createElement("datetime",date("d-m-Y H:i:s")));$com = $newItem->appendChild($xml->createElement("coment"));$com->appendChild($xml->createCDATASection($_POST["coment"]));$item->parentNode->replaceChild($newItem,$item);$xml->save($theXmlFile);}}
else{$xml=new XMLWriter();touch($theXmlFile);$theXmlFile = realpath($theXmlFile);$xml->openURI($theXmlFile);$xml->startDocument();$xml->startElement("files");$xml->endElement();$xml->endDocument();$xml->flush();}
if ($new){$xml = new DOMDocument("1.0", "utf-8");$xml->formatOutput = true;$xml->preserveWhiteSpace = false;$xml->load($theXmlFile);$newItem = $xml->createElement("file");$newItem->appendChild($xml->createElement("tab",$_POST["fType"]));$newItem->appendChild($xml->createElement("path",$newDir));$newItem->appendChild($xml->createElement("usr",$nus));$newItem->appendChild($xml->createElement("datetime",date("d-m-Y H:i:s")));$com = $newItem->appendChild($xml->createElement("coment"));$com->appendChild($xml->createCDATASection($_POST["coment"]));$xml->getElementsByTagName("files")->item(0)->insertBefore($newItem, $element);$xml->save($theXmlFile);}}
if($_GET["action"]=="download"){$ar=$_GET["Arquivo"];$ar="../".$ar;$separar=explode(".",basename($ar));$extension=strtolower($separar[1]);$extensiones_permitidas=array("text","jpg","gif","png","bmp","svg","mp4","ogv","webm","swf","txt","pdf","mp3","ogg","odt","ods","odp","sxw","sxc","sxi","zip","rar","tar","7z","gzip","bz2");
if (in_array($extension,$extensiones_permitidas)) {if(file_exists($ar)){$filepath = ($ar);header("HTTP/1.1 200 OK");header("Status: 200 OK");header("Content-Type: text/php");header('Content-Disposition: attachment; filename="'.basename($filepath).'"');header("Content-Length: ".filesize($filepath));readfile($filepath);}else{echo"El archivo: ".$ar." No existe";}}else{echo "El archivo: ".$ar." No Puede ser descargado";}}
if($_POST["action"]=="renameFile"){$file=$_POST["fName"];$file=str_replace("~", " ",$file);$file=str_replace("%20"," ",$file);if(is_writable("../".$file)){
if (rename("../".$file,"../".$_POST["newname"])){;$xmlF = simplexml_load_file("../".xmlFile);$cadena1='//path[.="../'.$file.'"]/parent::*';$result = $xmlF->xpath($cadena1);$result[0]->path="../".$_POST["newname"];$xmlF->asXML("../".xmlFile);}}}
if($_POST["action"]=="deleteFile"){$file=$_POST["fName"];$file=str_replace("~", " ",$file);$file=str_replace("%20"," ",$file);$com=$file;if(is_writable("../".$file)){$com="escribible";
if(unlink("../".$file)){$xmlF = simplexml_load_file("../".xmlFile);$cadena='//path[.="../'.$file.'"]/parent::*';$result = $xmlF->xpath($cadena);foreach ($result as $r) unset ($r[0]);$xmlF->asXML("../".xmlFile);$com="borrado";
$nus=decod($res["username"],keynum);$logFile = fopen(".."."/ardoraWorkFiles/deleted.log", "a") or die("Error creando archivo");fwrite($logFile,"\n"."==>".$nus."\n".date("d/m/Y H:i:s")." File-->".$file." IP:".getRealIP()) or die("Error escribiendo en el archivo");fclose($logFile);
}}}
function getRealIP() {if (!empty($_SERVER["HTTP_CLIENT_IP"])) return $_SERVER["HTTP_CLIENT_IP"];if (!empty($_SERVER["HTTP_X_FORWARDED_FOR"])) return $_SERVER["HTTP_X_FORWARDED_FOR"];return $_SERVER["REMOTE_ADDR"];}
if($_POST["action"]=="getInfoFile"){$file=$_POST["fName"];$file=str_replace("~", " ",$file);$file=str_replace("%20"," ",$file);$xml = new DOMDocument("1.0", "utf-8");$xml->load("../".xmlFile);
$query='//files/file[path="../'.$file.'"]';$xpath = new DOMXPath($xml);$result=$xpath->query($query);
if ($result->length>0){foreach ($result as $node) {$coment=$node->getElementsByTagName("coment")->item(0)->nodeValue;$usr=$node->getElementsByTagName("usr")->item(0)->nodeValue;$datetime=$node->getElementsByTagName("datetime")->item(0)->nodeValue;
$tab=$node->getElementsByTagName("tab")->item(0)->nodeValue;} echo json_encode(array("coment"=>$coment,"usr"=>$usr,"datetime"=>$datetime,"tab"=>$tab));}}
if($_POST["action"]=="logout"){session_start();$_SESSION = array();if (ini_get("session.use_cookies")) {$params = session_get_cookie_params();setcookie(session_name(),'', time() - 42000,$params["path"], $params["domain"],$params["secure"], $params["httponly"]);}
if (isset($_SERVER['HTTP_COOKIE'])) {$cookies = explode(';', $_SERVER['HTTP_COOKIE']);foreach($cookies as $cookie) {$parts=explode('=', $cookie);$name = trim($parts[0]);setcookie($name, null, time()-3600);setcookie($name, null, time()-3600, '/');}};session_destroy();$_SESSION["Username"]=NULL;echo json_encode(array("status" => "logout"));}
if($_POST["action"]=="getTxt"){$texto="";$handle=fopen("../".str_replace("%20"," ",$_POST["fName"]), "r");while (!feof($handle)) {$buffer = fgets($handle,4096);$texto=$texto.$buffer."<br/>";}
fclose($handle);$txt='<div align="justify" style="margin:5px;">'.utf8_encode($texto).'</div>';echo json_encode(array("txt"=>$txt));}
if($_POST["action"]=="moveFile"){$m_file=$_POST["m_file"];$m_dir=$_POST["m_dir"].$_POST["n_file"];$status="f";if (copy($m_file,$m_dir)){unlink($m_file);$status="t";$xml = new DOMDocument("1.0", "utf-8");
$xml->load("../".xmlFile);$files=$xml->getElementsByTagName("file");foreach($files as $file) {$f=$file->getElementsByTagName("path")->item(0)->nodeValue;if ($f==$m_file){$file->getElementsByTagName("path")->item(0)->nodeValue=$m_dir;}};$xml->save("../".xmlFile);};echo json_encode(array("status"=>$status));}
if($_POST["action"]=="copyFile"){$m_file=$_POST["m_file"];$m_dir=$_POST["m_dir"].$_POST["n_file"];$status="f";if (copy($m_file,$m_dir)){$status="t";$xml=new DOMDocument("1.0", "utf-8");$xml->load("../".xmlFile);
$files=$xml->getElementsByTagName("file");foreach($files as $file) {$f=$file->getElementsByTagName("path")->item(0)->nodeValue;if ($f==$m_file){$coment=$file->getElementsByTagName("coment")->item(0)->nodeValue;}}
$newItem = $xml->createElement("file");$newItem->appendChild($xml->createElement("tab",$_POST["fType"]));$newItem->appendChild($xml->createElement("path",$m_dir));$newItem->appendChild($xml->createElement("usr",decod($_SESSION["Username"],keynum)));$newItem->appendChild($xml->createElement("datetime",date("d-m-Y H:i:s")));
$com=$newItem->appendChild($xml->createElement("coment"));$com->appendChild($xml->createCDATASection($coment));$xml->getElementsByTagName("files")->item(0)->insertBefore($newItem, $element);$xml->save("../".xmlFile);};echo json_encode(array("status"=>$status));}
if($_POST["action"]=="rotateImg"){$nombre_archivo=$_POST["file"];$grados=$_POST["rot"];$type=$_POST["type"];if ($type=="jpg" || $type=="jpeg"){header("Content-type: image/jpeg");};if ($type=="png"){header("Content-type: image/png");};if ($type=="bmp"){header("Content-type: image/bmp");};if ($type=="svg"){header("Content-type: image/svg+xml");};
if ($type=="jpg" || $type=="jpeg"){$origen = imagecreatefromjpeg($nombre_archivo);}; if ($type=="png"){$origen = imagecreatefrompng($nombre_archivo);};if ($type=="bmp"){$origen = imagecreatefromwbmp($nombre_archivo);}
$rotar=imagerotate($origen, $grados, 0);if ($type=="jpg" || $type=="jpeg"){imagejpeg($rotar,$nombre_archivo);};if ($type=="png"){imagepng($rotar,$nombre_archivo);};if ($type=="bmp"){imagewbmp($rotar,$nombre_archivo);};
imagedestroy($origen);imagedestroy($rotar);echo json_encode(array("file"=>$nombre_archivo));}
?>
